package com.google.android.gms.internal;

import android.support.annotation.NonNull;
import com.google.android.gms.common.api.h;
import com.google.android.gms.common.api.i;
import com.google.android.gms.common.api.i.a;
import com.google.android.gms.common.api.m;
import com.google.android.gms.common.api.n;
import com.google.android.gms.common.api.p;
import com.google.android.gms.common.api.q;
import java.util.concurrent.TimeUnit;

public final class aio<R extends m> extends h<R> {
    private final ahn<R> a;

    public aio(i<R> iVar) {
        if (iVar instanceof ahn) {
            this.a = (ahn) iVar;
            return;
        }
        throw new IllegalArgumentException("OptionalPendingResult can only wrap PendingResults generated by an API call.");
    }

    public R a(long j, TimeUnit timeUnit) {
        return this.a.a(j, timeUnit);
    }

    @NonNull
    public <S extends m> q<S> a(@NonNull p<? super R, ? extends S> pVar) {
        return this.a.a(pVar);
    }

    public void a() {
        this.a.a();
    }

    public void a(a aVar) {
        this.a.a(aVar);
    }

    public void a(n<? super R> nVar) {
        this.a.a(nVar);
    }

    public void a(n<? super R> nVar, long j, TimeUnit timeUnit) {
        this.a.a(nVar, j, timeUnit);
    }

    public boolean b() {
        return this.a.i();
    }

    public R c() {
        if (b()) {
            return a(0, TimeUnit.MILLISECONDS);
        }
        throw new IllegalStateException("Result is not available. Check that isDone() returns true before calling get().");
    }

    public R d() {
        return this.a.d();
    }

    public boolean e() {
        return this.a.e();
    }

    public Integer f() {
        return this.a.f();
    }
}
