package com.google.android.gms.internal;

import android.content.Context;
import com.fimi.soul.service.CameraSocketService;
import com.google.android.gms.ads.internal.u;
import com.google.android.gms.cast.framework.media.NotificationOptions;
import com.tencent.mm.sdk.platformtools.Util;
import com.xiaomi.mistatistic.sdk.MiStatInterface;
import java.util.List;
import java.util.concurrent.TimeUnit;

@aaa
public final class uf {
    public static final ub<Long> A = ub.a(1, "gads:video:metric_frame_hash_time_leniency", 500);
    public static final ub<Boolean> B = ub.a(1, "gads:video:force_watermark", Boolean.valueOf(false));
    public static final ub<Boolean> C = ub.a(1, "gads:memory_bundle:debug_info", Boolean.valueOf(false));
    public static final ub<Boolean> D = ub.a(1, "gads:memory_bundle:runtime_info", Boolean.valueOf(true));
    public static final ub<String> E = ub.b(0, "gads:spam_ad_id_decorator:experiment_id");
    public static final ub<Boolean> F = ub.a(0, "gads:spam_ad_id_decorator:enabled", Boolean.valueOf(false));
    public static final ub<String> G = ub.b(0, "gads:looper_for_gms_client:experiment_id");
    public static final ub<Boolean> H = ub.a(0, "gads:looper_for_gms_client:enabled", Boolean.valueOf(true));
    public static final ub<Boolean> I = ub.a(0, "gads:sw_ad_request_service:enabled", Boolean.valueOf(true));
    public static final ub<Boolean> J = ub.a(0, "gads:sw_dynamite:enabled", Boolean.valueOf(true));
    public static final ub<String> K = ub.a(1, "gad:mraid:url_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_banner.js");
    public static final ub<String> L = ub.a(1, "gad:mraid:url_expanded_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_expanded_banner.js");
    public static final ub<String> M = ub.a(1, "gad:mraid:url_interstitial", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_interstitial.js");
    public static final ub<Boolean> N = ub.a(0, "gads:enabled_sdk_csi", Boolean.valueOf(false));
    public static final ub<String> O = ub.a(0, "gads:sdk_csi_server", "https://csi.gstatic.com/csi");
    public static final ub<Boolean> P = ub.a(0, "gads:sdk_csi_write_to_file", Boolean.valueOf(false));
    public static final ub<Boolean> Q = ub.a(0, "gads:enable_content_fetching", Boolean.valueOf(true));
    public static final ub<Integer> R = ub.a(0, "gads:content_length_weight", 1);
    public static final ub<Integer> S = ub.a(0, "gads:content_age_weight", 1);
    public static final ub<Integer> T = ub.a(0, "gads:min_content_len", 11);
    public static final ub<Integer> U = ub.a(0, "gads:fingerprint_number", 10);
    public static final ub<Integer> V = ub.a(0, "gads:sleep_sec", 10);
    public static final ub<Boolean> W = ub.a(0, "gad:app_index_enabled", Boolean.valueOf(true));
    public static final ub<Boolean> X = ub.a(0, "gads:app_index:without_content_info_present:enabled", Boolean.valueOf(true));
    public static final ub<Long> Y = ub.a(0, "gads:app_index:timeout_ms", 1000);
    public static final ub<String> Z = ub.a(0, "gads:app_index:experiment_id");
    public static final ub<String> a = ub.a(0, "gads:sdk_core_experiment_id");
    public static final ub<Integer> aA = ub.a(1, "gads:interstitial_ad_pool:max_pool_depth", 2);
    public static final ub<Integer> aB = ub.a(1, "gads:interstitial_ad_pool:time_limit_sec", (int) CameraSocketService.b);
    public static final ub<String> aC = ub.a(1, "gads:interstitial_ad_pool:ad_unit_exclusions", "(?!)");
    public static final ub<String> aD = ub.a(1, "gads:spherical_video:vertex_shader", "");
    public static final ub<String> aE = ub.a(1, "gads:spherical_video:fragment_shader", "");
    public static final ub<String> aF = ub.a(1, "gads:spherical_video:experiment_id");
    public static final ub<Boolean> aG = ub.a(0, "gads:log:verbose_enabled", Boolean.valueOf(false));
    public static final ub<Boolean> aH = ub.a(1, "gads:include_local_global_rectangles", Boolean.valueOf(false));
    public static final ub<String> aI = ub.a(1, "gads:include_local_global_rectangles:experiment_id");
    public static final ub<Boolean> aJ = ub.a(0, "gads:device_info_caching:enabled", Boolean.valueOf(true));
    public static final ub<Long> aK = ub.a(0, "gads:device_info_caching_expiry_ms:expiry", (long) MiStatInterface.MIN_UPLOAD_INTERVAL);
    public static final ub<Boolean> aL = ub.a(0, "gads:gen204_signals:enabled", Boolean.valueOf(false));
    public static final ub<Boolean> aM = ub.a(0, "gads:webview:error_reporting_enabled", Boolean.valueOf(false));
    public static final ub<Boolean> aN = ub.a(0, "gads:adid_reporting:enabled", Boolean.valueOf(false));
    public static final ub<Boolean> aO = ub.a(0, "gads:ad_settings_page_reporting:enabled", Boolean.valueOf(false));
    public static final ub<Boolean> aP = ub.a(0, "gads:adid_info_gmscore_upgrade_reporting:enabled", Boolean.valueOf(false));
    public static final ub<Boolean> aQ = ub.a(0, "gads:request_pkg:enabled", Boolean.valueOf(true));
    public static final ub<Boolean> aR = ub.a(1, "gads:gmsg:disable_back_button:enabled", Boolean.valueOf(true));
    public static final ub<Boolean> aS = ub.a(0, "gads:gmsg:video_meta:enabled", Boolean.valueOf(true));
    public static final ub<String> aT = ub.a(0, "gads:gmsg:video_meta:experiment_id");
    public static final ub<Long> aU = ub.a(0, "gads:network:cache_prediction_duration_s", 300);
    public static final ub<Boolean> aV = ub.a(0, "gads:mediation:dynamite_first:admobadapter", Boolean.valueOf(true));
    public static final ub<Boolean> aW = ub.a(0, "gads:mediation:dynamite_first:adurladapter", Boolean.valueOf(true));
    public static final ub<Long> aX = ub.a(0, "gads:ad_loader:timeout_ms", (long) Util.MILLSECONDS_OF_MINUTE);
    public static final ub<Long> aY = ub.a(0, "gads:rendering:timeout_ms", (long) Util.MILLSECONDS_OF_MINUTE);
    public static final ub<Boolean> aZ = ub.a(0, "gads:adshield:enable_adshield_instrumentation", Boolean.valueOf(false));
    public static final ub<String> aa = ub.a(0, "gads:kitkat_interstitial_workaround:experiment_id");
    public static final ub<Boolean> ab = ub.a(0, "gads:kitkat_interstitial_workaround:enabled", Boolean.valueOf(true));
    public static final ub<Boolean> ac = ub.a(0, "gads:interstitial_follow_url", Boolean.valueOf(true));
    public static final ub<Boolean> ad = ub.a(0, "gads:interstitial_follow_url:register_click", Boolean.valueOf(true));
    public static final ub<String> ae = ub.a(0, "gads:interstitial_follow_url:experiment_id");
    public static final ub<Boolean> af = ub.a(0, "gads:analytics_enabled", Boolean.valueOf(true));
    public static final ub<Boolean> ag = ub.a(0, "gads:ad_key_enabled", Boolean.valueOf(false));
    public static final ub<Integer> ah = ub.a(0, "gads:webview_cache_version", 0);
    public static final ub<Boolean> ai = ub.a(1, "gads:webview_recycle:enabled", Boolean.valueOf(false));
    public static final ub<String> aj = ub.a(1, "gads:webview_recycle:experiment_id");
    public static final ub<Boolean> ak = ub.a(1, "gads:webview:ignore_over_scroll", Boolean.valueOf(true));
    public static final ub<String> al = ub.b(0, "gads:pan:experiment_id");
    public static final ub<String> am = ub.a(1, "gads:rewarded:experiment_id");
    public static final ub<Long> an = ub.a(1, "gads:rewarded:adapter_timeout_ms", 20000);
    public static final ub<Boolean> ao = ub.a(1, "gads:app_activity_tracker:enabled", Boolean.valueOf(true));
    public static final ub<Long> ap = ub.a(1, "gads:app_activity_tracker:notify_background_listeners_delay_ms", 500);
    public static final ub<Long> aq = ub.a(1, "gads:app_activity_tracker:app_session_timeout_ms", TimeUnit.MINUTES.toMillis(5));
    public static final ub<Boolean> ar = ub.a(0, "gads:ad_manager_creator:enabled", Boolean.valueOf(true));
    public static final ub<String> as = ub.a(1, "gads:ad_manager_enforce_arp_invariant:experiment_id");
    public static final ub<Boolean> at = ub.a(1, "gads:ad_manager_enforce_arp_invariant:enabled", Boolean.valueOf(false));
    public static final ub<Long> au = ub.a(1, "gads:ad_overlay:delay_page_close_timeout_ms", 5000);
    public static final ub<Boolean> av = ub.a(1, "gads:interstitial_ad_pool:enabled", Boolean.valueOf(false));
    public static final ub<Boolean> aw = ub.a(1, "gads:interstitial_ad_pool:enabled_for_rewarded", Boolean.valueOf(false));
    public static final ub<String> ax = ub.a(1, "gads:interstitial_ad_pool:schema", "customTargeting");
    public static final ub<String> ay = ub.a(1, "gads:interstitial_ad_pool:request_exclusions", "com.google.ads.mediation.admob.AdMobAdapter/_ad");
    public static final ub<Integer> az = ub.a(1, "gads:interstitial_ad_pool:max_pools", 3);
    public static final ub<String> b = ub.a(0, "gads:sdk_core_location", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40.html");
    public static final ub<Boolean> bA = ub.a(0, "gads:support_screen_shot", Boolean.valueOf(true));
    public static final ub<Boolean> bB = ub.a(0, "gads:use_get_drawing_cache_for_screenshot:enabled", Boolean.valueOf(true));
    public static final ub<String> bC = ub.a(0, "gads:use_get_drawing_cache_for_screenshot:experiment_id");
    public static final ub<String> bD = ub.a(1, "gads:sdk_core_constants:experiment_id");
    public static final ub<String> bE = ub.a(1, "gads:sdk_core_constants:caps", "");
    public static final ub<Long> bF = ub.a(0, "gads:js_flags:update_interval", TimeUnit.HOURS.toMillis(12));
    public static final ub<Boolean> bG = ub.a(0, "gads:js_flags:mf", Boolean.valueOf(false));
    public static final ub<Boolean> bH = ub.a(0, "gads:custom_render:ping_on_ad_rendered", Boolean.valueOf(false));
    public static final ub<String> bI = ub.a(0, "gads:native:engine_url", "//googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html");
    public static final ub<String> bJ = ub.a(1, "gads:native:video_url", "//googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_video_ads.html");
    public static final ub<Boolean> bK = ub.a(1, "gads:singleton_webview_native", Boolean.valueOf(false));
    public static final ub<String> bL = ub.a(1, "gads:singleton_webview_native:experiment_id");
    public static final ub<Boolean> bM = ub.a(1, "gads:enable_untrack_view_native", Boolean.valueOf(true));
    public static final ub<Boolean> bN = ub.a(1, "gads:reset_listeners_preparead_native", Boolean.valueOf(true));
    public static final ub<Integer> bO = ub.a(1, "gads:native_video_load_timeout", 10);
    public static final ub<String> bP = ub.a(1, "gads:native_video_load_timeout:experiment_id");
    public static final ub<String> bQ = ub.a(1, "gads:ad_choices_content_description", "Ad Choices Icon");
    public static final ub<Boolean> bR = ub.a(1, "gads:clamp_native_video_player_dimensions", Boolean.valueOf(true));
    public static final ub<Boolean> bS = ub.a(1, "gads:fluid_ad:use_wrap_content_height", Boolean.valueOf(false));
    public static final ub<Boolean> bT = ub.a(0, "gads:method_tracing:enabled", Boolean.valueOf(false));
    public static final ub<Long> bU = ub.a(0, "gads:method_tracing:duration_ms", (long) NotificationOptions.b);
    public static final ub<Integer> bV = ub.a(0, "gads:method_tracing:count", 5);
    public static final ub<Integer> bW = ub.a(0, "gads:method_tracing:filesize", 134217728);
    public static final ub<Boolean> bX = ub.a(1, "gads:auto_location_for_coarse_permission", Boolean.valueOf(false));
    public static final ub<String> bY = ub.b(1, "gads:auto_location_for_coarse_permission:experiment_id");
    public static final ub<Long> bZ = ub.a(1, "gads:auto_location_timeout", 2000);
    public static final ub<Long> ba = ub.a(1, "gads:gestures:task_timeout", 2000);
    public static final ub<String> bb = ub.a(1, "gads:gestures:encrypt_size_limit:experiment_id");
    public static final ub<Boolean> bc = ub.a(1, "gads:gestures:encrypt_size_limit:enabled", Boolean.valueOf(false));
    public static final ub<String> bd = ub.a(1, "gads:gestures:appid:experiment_id");
    public static final ub<Boolean> be = ub.a(1, "gads:gestures:appid:enabled", Boolean.valueOf(false));
    public static final ub<Boolean> bf = ub.a(0, "gads:gestures:v6:enabled", Boolean.valueOf(false));
    public static final ub<String> bg = ub.a(1, "gads:gestures:usb_query:experiment_id");
    public static final ub<Boolean> bh = ub.a(1, "gads:gestures:usb_query:enabled", Boolean.valueOf(false));
    public static final ub<String> bi = ub.a(1, "gads:gestures:usb_click:experiment_id");
    public static final ub<Boolean> bj = ub.a(1, "gads:gestures:usb_click:enabled", Boolean.valueOf(false));
    public static final ub<Boolean> bk = ub.a(1, "gads:gestures:touchinfo:enabled", Boolean.valueOf(false));
    public static final ub<String> bl = ub.a(1, "gads:gestures:touchinfo:experiment_id");
    public static final ub<Boolean> bm = ub.a(1, "gads:gestures:clock_query:enabled", Boolean.valueOf(false));
    public static final ub<String> bn = ub.a(1, "gads:gestures:clock_query:experiment_id");
    public static final ub<Boolean> bo = ub.a(1, "gads:gestures:clock_click:enabled", Boolean.valueOf(false));
    public static final ub<String> bp = ub.a(1, "gads:gestures:clock_click:experiment_id");
    public static ub<Boolean> bq = ub.a(1, "gads:gestures:btl_click:enabled", Boolean.valueOf(false));
    public static ub<String> br = ub.a(1, "gads:gestures:btl_click:experiment_id");
    public static final ub<String> bs = ub.a(1, "gads:gestures:click_stk:experiment_id");
    public static final ub<Boolean> bt = ub.a(1, "gads:gestures:click_stk:enabled", Boolean.valueOf(true));
    public static final ub<Boolean> bu = ub.a(0, "gass:client:enabled", Boolean.valueOf(true));
    public static final ub<String> bv = ub.a(0, "gass:client:experiment_id");
    public static final ub<Boolean> bw = ub.a(0, "gass:enabled", Boolean.valueOf(true));
    public static final ub<Boolean> bx = ub.a(0, "gass:enable_int_signal", Boolean.valueOf(true));
    public static final ub<Boolean> by = ub.a(0, "gads:adid_notification:first_party_check:enabled", Boolean.valueOf(true));
    public static final ub<Boolean> bz = ub.a(0, "gads:edu_device_helper:enabled", Boolean.valueOf(true));
    public static final ub<Boolean> c = ub.a(0, "gads:request_builder:singleton_webview", Boolean.valueOf(false));
    public static final ub<Long> cA = ub.a(1, "gads:cache:bind_on_request_keep_alive", TimeUnit.SECONDS.toMillis(30));
    public static final ub<Boolean> cB = ub.a(1, "gads:cache:use_cache_data_source", Boolean.valueOf(false));
    public static final ub<Boolean> cC = ub.a(1, "gads:chrome_custom_tabs:enabled", Boolean.valueOf(true));
    public static final ub<Boolean> cD = ub.a(1, "gads:drx_debug:enabled", Boolean.valueOf(false));
    public static final ub<String> cE = ub.a(1, "gads:drx_debug:debug_device_linking_url", "https://www.google.com/dfp/linkDevice");
    public static final ub<String> cF = ub.a(1, "gads:drx_debug:in_app_preview_status_url", "https://www.google.com/dfp/inAppPreview");
    public static final ub<String> cG = ub.a(1, "gads:drx_debug:debug_signal_status_url", "https://www.google.com/dfp/debugSignals");
    public static final ub<String> cH = ub.a(1, "gads:drx_debug:send_debug_data_url", "https://www.google.com/dfp/sendDebugData");
    public static final ub<Integer> cI = ub.a(1, "gads:drx_debug:timeout_ms", 5000);
    public static final ub<Integer> cJ = ub.a(1, "gad:pixel_dp_comparision_multiplier", 1);
    public static final ub<Boolean> cK = ub.a(1, "gad:interstitial_for_multi_window", Boolean.valueOf(false));
    public static final ub<String> ca = ub.b(1, "gads:auto_location_timeout:experiment_id");
    public static final ub<Long> cb = ub.a(1, "gads:auto_location_interval", -1);
    public static final ub<String> cc = ub.b(1, "gads:auto_location_interval:experiment_id");
    public static final ub<Boolean> cd = ub.a(1, "gads:fetch_app_settings_using_cld:enabled", Boolean.valueOf(false));
    public static final ub<String> ce = ub.a(1, "gads:fetch_app_settings_using_cld:enabled:experiment_id");
    public static final ub<Long> cf = ub.a(1, "gads:fetch_app_settings_using_cld:refresh_interval_ms", 7200000);
    public static final ub<String> cg = ub.a(1, "gads:fetch_app_settings_using_cld:refresh_interval_ms:experiment_id");
    public static final ub<String> ch = ub.a(0, "gads:afs:csa:experiment_id");
    public static final ub<String> ci = ub.a(0, "gads:afs:csa_webview_gmsg_ad_failed", "gmsg://noAdLoaded");
    public static final ub<String> cj = ub.a(0, "gads:afs:csa_webview_gmsg_script_load_failed", "gmsg://scriptLoadFailed");
    public static final ub<String> ck = ub.a(0, "gads:afs:csa_webview_gmsg_ad_loaded", "gmsg://adResized");
    public static final ub<String> cl = ub.a(0, "gads:afs:csa_webview_static_file_path", "/afs/ads/i/webview.html");
    public static final ub<String> cm = ub.a(0, "gads:afs:csa_webview_custom_domain_param_key", "csa_customDomain");
    public static final ub<Long> cn = ub.a(0, "gads:afs:csa_webview_adshield_timeout_ms", 1000);
    public static final ub<Boolean> co = ub.a(0, "gads:afs:csa_ad_manager_enabled", Boolean.valueOf(true));
    public static final ub<Boolean> cp = ub.a(1, "gads:parental_controls:send_from_client", Boolean.valueOf(true));
    public static final ub<Long> cq = ub.a(1, "gads:parental_controls:timeout", 2000);
    public static final ub<String> cr = ub.a(0, "gads:safe_browsing:api_key", "AIzaSyDRKQ9d6kfsoZT2lUnZcZnBYvH69HExNPE");
    public static final ub<Long> cs = ub.a(0, "gads:safe_browsing:safety_net:delay_ms", 2000);
    public static final ub<Boolean> ct = ub.a(0, "gads:safe_browsing:debug", Boolean.valueOf(false));
    public static final ub<Boolean> cu = ub.a(0, "gads:webview_cookie:enabled", Boolean.valueOf(true));
    public static final ub<Integer> cv = ub.a(1, "gads:cache:max_concurrent_downloads", 10);
    public static final ub<Long> cw = ub.a(1, "gads:cache:javascript_timeout_millis", 5000);
    public static final ub<Boolean> cx = ub.a(1, "gads:cache:bind_on_foreground", Boolean.valueOf(false));
    public static final ub<Boolean> cy = ub.a(1, "gads:cache:bind_on_init", Boolean.valueOf(false));
    public static final ub<Boolean> cz = ub.a(1, "gads:cache:bind_on_request", Boolean.valueOf(false));
    public static final ub<String> d = ub.a(0, "gads:request_builder:singleton_webview_experiment_id");
    public static final ub<Boolean> e = ub.a(0, "gads:sdk_use_dynamic_module", Boolean.valueOf(true));
    public static final ub<String> f = ub.a(0, "gads:sdk_use_dynamic_module_experiment_id");
    public static final ub<Boolean> g = ub.a(0, "gads:sdk_crash_report_enabled", Boolean.valueOf(false));
    public static final ub<Boolean> h = ub.a(0, "gads:sdk_crash_report_full_stacktrace", Boolean.valueOf(false));
    public static final ub<String> i = ub.a(0, "gads:sdk_crash_report_class_prefix", "com.google.");
    public static final ub<Boolean> j = ub.a(0, "gads:block_autoclicks", Boolean.valueOf(false));
    public static final ub<String> k = ub.a(0, "gads:block_autoclicks_experiment_id");
    public static final ub<String> l = ub.b(0, "gads:prefetch:experiment_id");
    public static final ub<String> m = ub.a(0, "gads:spam_app_context:experiment_id");
    public static final ub<Boolean> n = ub.a(1, "gads:spam_app_context:enabled", Boolean.valueOf(false));
    public static final ub<Integer> o = ub.a(1, "gads:http_url_connection_factory:timeout_millis", 10000);
    public static final ub<String> p = ub.a(1, "gads:video_exo_player:version", "1");
    public static final ub<String> q = ub.a(0, "gads:video_stream_cache:experiment_id");
    public static final ub<Integer> r = ub.a(1, "gads:video_stream_cache:limit_count", 5);
    public static final ub<Integer> s = ub.a(1, "gads:video_stream_cache:limit_space", 8388608);
    public static final ub<Integer> t = ub.a(1, "gads:video_stream_exo_allocator:segment_size", 65536);
    public static final ub<Integer> u = ub.a(1, "gads:video_stream_exo_cache:buffer_size", 8388608);
    public static final ub<Long> v = ub.a(1, "gads:video_stream_cache:limit_time_sec", 300);
    public static final ub<Long> w = ub.a(1, "gads:video_stream_cache:notify_interval_millis", 1000);
    public static final ub<Integer> x = ub.a(1, "gads:video_stream_cache:connect_timeout_millis", 10000);
    public static final ub<Boolean> y = ub.a(0, "gads:video:metric_reporting_enabled", Boolean.valueOf(false));
    public static final ub<String> z = ub.a(1, "gads:video:metric_frame_hash_times", "");

    public static List<String> a() {
        return u.p().a();
    }

    public static void a(Context context) {
        acj.a(new 1(context));
    }

    public static List<String> b() {
        return u.p().b();
    }
}
