.class public final Lcom/google/android/gms/internal/aio;
.super Lcom/google/android/gms/common/api/h;


# annotations
.annotation system Ldalvik/annotation/Signature;
    value = {
        "<R::",
        "Lcom/google/android/gms/common/api/m;",
        ">",
        "Lcom/google/android/gms/common/api/h",
        "<TR;>;"
    }
.end annotation


# instance fields
.field private final a:Lcom/google/android/gms/internal/ahn;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "Lcom/google/android/gms/internal/ahn",
            "<TR;>;"
        }
    .end annotation
.end field


# direct methods
.method public constructor <init>(Lcom/google/android/gms/common/api/i;)V
    .locals 2
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Lcom/google/android/gms/common/api/i",
            "<TR;>;)V"
        }
    .end annotation

    invoke-direct {p0}, Lcom/google/android/gms/common/api/h;-><init>()V

    instance-of v0, p1, Lcom/google/android/gms/internal/ahn;

    if-nez v0, :cond_0

    new-instance v0, Ljava/lang/IllegalArgumentException;

    const-string v1, "OptionalPendingResult can only wrap PendingResults generated by an API call."

    invoke-direct {v0, v1}, Ljava/lang/IllegalArgumentException;-><init>(Ljava/lang/String;)V

    throw v0

    :cond_0
    check-cast p1, Lcom/google/android/gms/internal/ahn;

    iput-object p1, p0, Lcom/google/android/gms/internal/aio;->a:Lcom/google/android/gms/internal/ahn;

    return-void
.end method


# virtual methods
.method public a(JLjava/util/concurrent/TimeUnit;)Lcom/google/android/gms/common/api/m;
    .locals 1
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(J",
            "Ljava/util/concurrent/TimeUnit;",
            ")TR;"
        }
    .end annotation

    iget-object v0, p0, Lcom/google/android/gms/internal/aio;->a:Lcom/google/android/gms/internal/ahn;

    invoke-virtual {v0, p1, p2, p3}, Lcom/google/android/gms/internal/ahn;->a(JLjava/util/concurrent/TimeUnit;)Lcom/google/android/gms/common/api/m;

    move-result-object v0

    return-object v0
.end method

.method public a(Lcom/google/android/gms/common/api/p;)Lcom/google/android/gms/common/api/q;
    .locals 1
    .param p1    # Lcom/google/android/gms/common/api/p;
        .annotation build Landroid/support/annotation/NonNull;
        .end annotation
    .end param
    .annotation build Landroid/support/annotation/NonNull;
    .end annotation

    .annotation system Ldalvik/annotation/Signature;
        value = {
            "<S::",
            "Lcom/google/android/gms/common/api/m;",
            ">(",
            "Lcom/google/android/gms/common/api/p",
            "<-TR;+TS;>;)",
            "Lcom/google/android/gms/common/api/q",
            "<TS;>;"
        }
    .end annotation

    iget-object v0, p0, Lcom/google/android/gms/internal/aio;->a:Lcom/google/android/gms/internal/ahn;

    invoke-virtual {v0, p1}, Lcom/google/android/gms/internal/ahn;->a(Lcom/google/android/gms/common/api/p;)Lcom/google/android/gms/common/api/q;

    move-result-object v0

    return-object v0
.end method

.method public a()V
    .locals 1

    iget-object v0, p0, Lcom/google/android/gms/internal/aio;->a:Lcom/google/android/gms/internal/ahn;

    invoke-virtual {v0}, Lcom/google/android/gms/internal/ahn;->a()V

    return-void
.end method

.method public a(Lcom/google/android/gms/common/api/i$a;)V
    .locals 1

    iget-object v0, p0, Lcom/google/android/gms/internal/aio;->a:Lcom/google/android/gms/internal/ahn;

    invoke-virtual {v0, p1}, Lcom/google/android/gms/internal/ahn;->a(Lcom/google/android/gms/common/api/i$a;)V

    return-void
.end method

.method public a(Lcom/google/android/gms/common/api/n;)V
    .locals 1
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Lcom/google/android/gms/common/api/n",
            "<-TR;>;)V"
        }
    .end annotation

    iget-object v0, p0, Lcom/google/android/gms/internal/aio;->a:Lcom/google/android/gms/internal/ahn;

    invoke-virtual {v0, p1}, Lcom/google/android/gms/internal/ahn;->a(Lcom/google/android/gms/common/api/n;)V

    return-void
.end method

.method public a(Lcom/google/android/gms/common/api/n;JLjava/util/concurrent/TimeUnit;)V
    .locals 2
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Lcom/google/android/gms/common/api/n",
            "<-TR;>;J",
            "Ljava/util/concurrent/TimeUnit;",
            ")V"
        }
    .end annotation

    iget-object v0, p0, Lcom/google/android/gms/internal/aio;->a:Lcom/google/android/gms/internal/ahn;

    invoke-virtual {v0, p1, p2, p3, p4}, Lcom/google/android/gms/internal/ahn;->a(Lcom/google/android/gms/common/api/n;JLjava/util/concurrent/TimeUnit;)V

    return-void
.end method

.method public b()Z
    .locals 1

    iget-object v0, p0, Lcom/google/android/gms/internal/aio;->a:Lcom/google/android/gms/internal/ahn;

    invoke-virtual {v0}, Lcom/google/android/gms/internal/ahn;->i()Z

    move-result v0

    return v0
.end method

.method public c()Lcom/google/android/gms/common/api/m;
    .locals 3
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "()TR;"
        }
    .end annotation

    invoke-virtual {p0}, Lcom/google/android/gms/internal/aio;->b()Z

    move-result v0

    if-eqz v0, :cond_0

    const-wide/16 v0, 0x0

    sget-object v2, Ljava/util/concurrent/TimeUnit;->MILLISECONDS:Ljava/util/concurrent/TimeUnit;

    invoke-virtual {p0, v0, v1, v2}, Lcom/google/android/gms/internal/aio;->a(JLjava/util/concurrent/TimeUnit;)Lcom/google/android/gms/common/api/m;

    move-result-object v0

    return-object v0

    :cond_0
    new-instance v0, Ljava/lang/IllegalStateException;

    const-string v1, "Result is not available. Check that isDone() returns true before calling get()."

    invoke-direct {v0, v1}, Ljava/lang/IllegalStateException;-><init>(Ljava/lang/String;)V

    throw v0
.end method

.method public d()Lcom/google/android/gms/common/api/m;
    .locals 1
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "()TR;"
        }
    .end annotation

    iget-object v0, p0, Lcom/google/android/gms/internal/aio;->a:Lcom/google/android/gms/internal/ahn;

    invoke-virtual {v0}, Lcom/google/android/gms/internal/ahn;->d()Lcom/google/android/gms/common/api/m;

    move-result-object v0

    return-object v0
.end method

.method public e()Z
    .locals 1

    iget-object v0, p0, Lcom/google/android/gms/internal/aio;->a:Lcom/google/android/gms/internal/ahn;

    invoke-virtual {v0}, Lcom/google/android/gms/internal/ahn;->e()Z

    move-result v0

    return v0
.end method

.method public f()Ljava/lang/Integer;
    .locals 1

    iget-object v0, p0, Lcom/google/android/gms/internal/aio;->a:Lcom/google/android/gms/internal/ahn;

    invoke-virtual {v0}, Lcom/google/android/gms/internal/ahn;->f()Ljava/lang/Integer;

    move-result-object v0

    return-object v0
.end method
