package com.google.android.gms.games.internal.player;

import android.text.TextUtils;

public final class b {
    public final String A;
    public final String B;
    public final String C;
    public final String D;
    public final String E;
    public final String F;
    public final String G;
    public final String H;
    public final String I;
    public final String a;
    public final String b;
    public final String c;
    public final String d;
    public final String e;
    public final String f;
    public final String g;
    public final String h;
    public final String i;
    public final String j;
    public final String k;
    public final String l;
    public final String m;
    public final String n;
    public final String o;
    public final String p;
    public final String q;
    public final String r;
    public final String s;
    public final String t;
    public final String u;
    public final String v;
    public final String w;
    public final String x;
    public final String y;
    public final String z;

    public b(String str) {
        if (TextUtils.isEmpty(str)) {
            this.a = "external_player_id";
            this.b = "profile_name";
            this.c = "profile_icon_image_uri";
            this.d = "profile_icon_image_url";
            this.e = "profile_hi_res_image_uri";
            this.f = "profile_hi_res_image_url";
            this.g = "last_updated";
            this.h = "is_in_circles";
            this.i = "played_with_timestamp";
            this.j = "current_xp_total";
            this.k = "current_level";
            this.l = "current_level_min_xp";
            this.m = "current_level_max_xp";
            this.n = "next_level";
            this.o = "next_level_max_xp";
            this.p = "last_level_up_timestamp";
            this.q = "player_title";
            this.r = "has_all_public_acls";
            this.s = "is_profile_visible";
            this.t = "most_recent_external_game_id";
            this.u = "most_recent_game_name";
            this.v = "most_recent_activity_timestamp";
            this.w = "most_recent_game_icon_uri";
            this.x = "most_recent_game_hi_res_uri";
            this.y = "most_recent_game_featured_uri";
            this.z = "has_debug_access";
            this.A = "gamer_tag";
            this.B = "real_name";
            this.C = "banner_image_landscape_uri";
            this.D = "banner_image_landscape_url";
            this.E = "banner_image_portrait_uri";
            this.F = "banner_image_portrait_url";
            this.G = "gamer_friend_status";
            this.H = "gamer_friend_update_timestamp";
            this.I = "is_muted";
            return;
        }
        String valueOf = String.valueOf(str);
        String valueOf2 = String.valueOf("external_player_id");
        this.a = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("profile_name");
        this.b = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("profile_icon_image_uri");
        this.c = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("profile_icon_image_url");
        this.d = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("profile_hi_res_image_uri");
        this.e = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("profile_hi_res_image_url");
        this.f = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("last_updated");
        this.g = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("is_in_circles");
        this.h = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("played_with_timestamp");
        this.i = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("current_xp_total");
        this.j = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("current_level");
        this.k = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("current_level_min_xp");
        this.l = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("current_level_max_xp");
        this.m = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("next_level");
        this.n = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("next_level_max_xp");
        this.o = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("last_level_up_timestamp");
        this.p = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("player_title");
        this.q = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("has_all_public_acls");
        this.r = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("is_profile_visible");
        this.s = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("most_recent_external_game_id");
        this.t = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("most_recent_game_name");
        this.u = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("most_recent_activity_timestamp");
        this.v = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("most_recent_game_icon_uri");
        this.w = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("most_recent_game_hi_res_uri");
        this.x = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("most_recent_game_featured_uri");
        this.y = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("has_debug_access");
        this.z = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("gamer_tag");
        this.A = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("real_name");
        this.B = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("banner_image_landscape_uri");
        this.C = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("banner_image_landscape_url");
        this.D = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("banner_image_portrait_uri");
        this.E = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("banner_image_portrait_url");
        this.F = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("gamer_friend_status");
        this.G = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("gamer_friend_update_timestamp");
        this.H = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("is_muted");
        this.I = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
    }
}
